#!/bin/sh

ARCH=$1

tar zcf target/ble-scanner.$ARCH.tar.gz \
  --transform "s,^contrib/ble-scanner.service,/etc/systemd/system/ble-scanner.service," \
  misc/ble-scanner.service \
  --transform "s,^target/$ARCH/release/ble-scanner,/opt/ble-scanner/bin/ble-scanner," \
  target/$ARCH/release/ble-scanner
